### PR TITLE
Update data

### PR DESCRIPTION
**Pull request by JMurphyWeb**
Update the data to new data structure

### CODE REVIEW

**Comment by JMurphyWeb** [comment]
Why do we need to?

**Comment by SimonLab** [comment]
To publish on npm?

**Comment by JMurphyWeb** [comment]
but it only has some tests changed. Do we need to republish?

**Comment by SimonLab** [comment]
I tend to have a new version when a new PR is created, this keep the npm package synchronised with the master branch. Merging now to not block you and let's update the version and package on the next PR :+1:

**Pull request merged**
